### ISSUE TITLE
Wrong tips on "Writing cross-platform Node.js"

### ISSUE THREAD

**Issue by cranic** [shapeshed/flim.shapeshed.com#13]
Everything that you teached about paths is wrong. In Windows this will work:

``` javascript
fs.readFileSync('C:/User/Admin/myfile.txt');

// or this
fs.readFileSync('./myfile.txt');

// and even this
fs.readFileSync('C:\\User/Admin\\myfile.txt');
```

You should try your code before teaching wrong things over the internet.

**Comment by shapeshed** [comment]
Thanks for the feeback. Incorporated in df814da9441497f77045096d6ef7c0f39c5aeb15
